// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820182608_AddMatriculaToLoginCertification")]
    partial class AddMatriculaToLoginCertification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QualityCertificateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalisePo")
                        .HasColumnType("text");

                    b.Property<int?>("AnalystId")
                        .HasColumnType("integer");

                    b.Property<string>("AnalystName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CDChamado")
                        .HasColumnType("text");

                    b.Property<string>("CertificadoMP")
                        .HasColumnType("text");

                    b.Property<string>("Cliente")
                        .HasColumnType("text");

                    b.Property<string>("CodigoCliente")
                        .HasColumnType("text");

                    b.Property<int?>("ControleElebId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreateDate");

                    b.Property<DateTime?>("Data")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Decapagem")
                        .HasColumnType("text");

                    b.Property<string>("DescricaoOperacao")
                        .HasColumnType("text");

                    b.Property<string>("DesenhoLP")
                        .HasColumnType("text");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Lote")
                        .HasColumnType("text");

                    b.Property<string>("NumeroCertificado")
                        .HasColumnType("text");

                    b.Property<string>("OC")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Ordem")
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text");

                    b.Property<string>("Quantidade")
                        .HasColumnType("text");

                    b.Property<string>("RelatorioInspecao")
                        .HasColumnType("text");

                    b.Property<string>("Responsavel")
                        .HasColumnType("text");

                    b.Property<string>("RevisaoDesenho")
                        .HasColumnType("text");

                    b.Property<string>("SNDecapagem")
                        .HasColumnType("text");

                    b.Property<string>("SNPeca")
                        .HasColumnType("text");

                    b.Property<string>("TipoEnvio")
                        .HasColumnType("text");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValorPeca")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QualityCertificates");
                });

            modelBuilder.Entity("backend.Models.AnalystCertificateModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnalystsId")
                        .HasColumnType("integer")
                        .HasColumnName("AnalystsId");

                    b.Property<int>("Certificate")
                        .HasColumnType("integer");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnalystsId");

                    b.HasIndex("Certificate", "IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = FALSE AND \"IsDefault\" = TRUE");

                    b.ToTable("AnalystsCertificate");
                });

            modelBuilder.Entity("backend.Models.AnalystModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Analyst")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Analysts");
                });

            modelBuilder.Entity("backend.Models.ClienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("backend.Models.ControleEleb", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AnalisePo")
                        .HasColumnType("text")
                        .HasColumnName("Analise_PO");

                    b.Property<string>("Cd")
                        .HasColumnType("text")
                        .HasColumnName("CD");

                    b.Property<string>("Cliente")
                        .HasColumnType("text")
                        .HasColumnName("Cliente");

                    b.Property<string>("CodEleb")
                        .HasColumnType("text")
                        .HasColumnName("COD_ELEB");

                    b.Property<DateTime?>("DataEnvioParaEleb")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Data_Envio_para_ELEB");

                    b.Property<string>("Decapagem")
                        .HasColumnType("text")
                        .HasColumnName("Decapagem");

                    b.Property<string>("NfFaturada")
                        .HasColumnType("text")
                        .HasColumnName("NF_Faturada");

                    b.Property<string>("NumCertificado")
                        .HasColumnType("text")
                        .HasColumnName("Num_Certificado");

                    b.Property<string>("OpDigicon")
                        .HasColumnType("text")
                        .HasColumnName("OP_Digicon");

                    b.Property<string>("OpEleb")
                        .HasColumnType("text")
                        .HasColumnName("OP_ELEB");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text")
                        .HasColumnName("Part_Number");

                    b.Property<string>("PoEleb")
                        .HasColumnType("text")
                        .HasColumnName("PO_ELEB");

                    b.Property<string>("QtdLote")
                        .HasColumnType("text")
                        .HasColumnName("Qtd_Lote");

                    b.Property<string>("QtdSaldo")
                        .HasColumnType("text")
                        .HasColumnName("Qtd_Saldo");

                    b.Property<string>("QtdSaldo1")
                        .HasColumnType("text")
                        .HasColumnName("Qtd_Saldo1");

                    b.Property<string>("RevisaoDesenho")
                        .HasColumnType("text")
                        .HasColumnName("Revisao_Desenho");

                    b.Property<string>("Situacao")
                        .HasColumnType("text")
                        .HasColumnName("Situacao");

                    b.Property<string>("SnDecap")
                        .HasColumnType("text")
                        .HasColumnName("SN_Decap");

                    b.Property<string>("SnPeca")
                        .HasColumnType("text")
                        .HasColumnName("SN_Peca");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text")
                        .HasColumnName("UpdateBy");

                    b.Property<string>("ValorPeca")
                        .HasColumnType("text")
                        .HasColumnName("Valor_Peca");

                    b.Property<string>("lote")
                        .HasColumnType("text")
                        .HasColumnName("Lote_ELEB");

                    b.HasKey("ID");

                    b.ToTable("Controle_Eleb");
                });

            modelBuilder.Entity("backend.Models.LoginCertificationModel", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("matricula");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("salt");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasFilter("\"matricula\" IS NOT NULL");

                    b.ToTable("login_certification", (string)null);
                });

            modelBuilder.Entity("backend.Models.LoginModulePermissionModel", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.Property<string>("ModuleKey")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modulekey");

                    b.Property<bool>("CanEdit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("canedit");

                    b.Property<bool>("CanView")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("canview");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Username", "ModuleKey");

                    b.HasIndex("Username");

                    b.ToTable("login_module_permissions", (string)null);
                });

            modelBuilder.Entity("backend.Models.LoginPasswordResetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiresat");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tokenhash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("usedat");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("Username", "Email");

                    b.ToTable("login_password_resets", (string)null);
                });

            modelBuilder.Entity("backend.Models.LoginSessionModel", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sessionid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ipaddress");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastseen");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revokedat");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("useragent");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.HasKey("SessionId");

                    b.HasIndex("LastSeen");

                    b.HasIndex("Username");

                    b.ToTable("login_sessions", (string)null);
                });

            modelBuilder.Entity("backend.Models.NormaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Norma")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Processo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Revision")
                        .HasColumnType("text");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TechnicalStandards");
                });

            modelBuilder.Entity("backend.Models.OperationProcessModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OperationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperationQuantity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OperationProcess");
                });

            modelBuilder.Entity("backend.Models.ParameterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Norma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormaRevision")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Processo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("backend.Models.PartNumberHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Changes")
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<int>("PartNumberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartNumberId");

                    b.ToTable("History_PartNumber");
                });

            modelBuilder.Entity("backend.Models.PartNumberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("ClienteNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrawingRevision")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Revision")
                        .HasColumnType("text");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PartNumbers");
                });

            modelBuilder.Entity("backend.Models.ProductConformityCertificateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalystId")
                        .HasColumnType("integer");

                    b.Property<string>("AnalystName")
                        .HasColumnType("text");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("text");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerPO")
                        .HasColumnType("text");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text");

                    b.Property<string>("DocumentRevision")
                        .HasColumnType("text");

                    b.Property<DateTime>("EmissionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InspectedAccording")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNumberDescription")
                        .HasColumnType("text");

                    b.Property<int?>("PartNumberId")
                        .HasColumnType("integer");

                    b.Property<string>("PartNumberRevision")
                        .HasColumnType("text");

                    b.Property<string>("Quantity")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductConformityCertificates");
                });

            modelBuilder.Entity("backend.Models.ProductDocumentControlModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentRevision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InspectedAccording")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductDocumentControls");
                });

            modelBuilder.Entity("backend.Models.PurchaseOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("ClienteNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PONumber", "Item", "ClienteId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = FALSE");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("backend.Models.RncModel", b =>
                {
                    b.Property<string>("Cause")
                        .HasColumnType("text")
                        .HasColumnName("Data2");

                    b.Property<string>("Client")
                        .HasColumnType("text")
                        .HasColumnName("Cliente");

                    b.Property<string>("Machine")
                        .HasColumnType("text")
                        .HasColumnName("CodeMach");

                    b.Property<DateTime?>("NonConformityDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DataGerado");

                    b.Property<int?>("NonConformityQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("QntdNC");

                    b.Property<string>("Operator")
                        .HasColumnType("text")
                        .HasColumnName("Operator");

                    b.Property<string>("Origin")
                        .HasColumnType("text")
                        .HasColumnName("Causador");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text")
                        .HasColumnName("IndProd3");

                    b.Property<string>("ProductionOrder")
                        .HasColumnType("text")
                        .HasColumnName("IndProd1");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("Data1");

                    b.ToTable("RNC", (string)null);
                });

            modelBuilder.Entity("backend.Models.ShippingLabelModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssyHeaderPrefix")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("BadgeBold")
                        .HasColumnType("boolean");

                    b.Property<string>("BadgeFontFamily")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("BadgeFontMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BadgeHeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BadgeLeftMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BadgeStrokeWidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("BadgeTopMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BadgeWidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("CountryBold")
                        .HasColumnType("boolean");

                    b.Property<string>("CountryFontFamily")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("CountryFontMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CountryLeftMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CountryRightMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CountryText")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("CountryTopMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HeaderBold")
                        .HasColumnType("boolean");

                    b.Property<string>("HeaderFontFamily")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("HeaderFontMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HeaderLeftMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HeaderPrefix")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("HeaderRightMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HeaderTopMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LabelHeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LabelModel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("LabelWidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("MarginBottomMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MarginLeftMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MarginRightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MarginTopMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("PartNumberId")
                        .HasColumnType("integer");

                    b.Property<string>("PrinterName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RangeEnd")
                        .HasColumnType("integer");

                    b.Property<int>("RangeStart")
                        .HasColumnType("integer");

                    b.Property<bool>("ReferenceBold")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReferenceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReferenceFontFamily")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("ReferenceFontMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ReferenceLeftMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ReferenceRightMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ReferenceTopMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("WarningBold")
                        .HasColumnType("boolean");

                    b.Property<string>("WarningFontFamily")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("WarningFontMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WarningLeftMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WarningRightMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("WarningText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("WarningTopMm")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ShippingLabels");
                });

            modelBuilder.Entity("backend.Models.ShippingLabelPrintSettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssyHeaderPrefix")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("BadgeBold")
                        .HasColumnType("boolean");

                    b.Property<string>("BadgeFontFamily")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("BadgeFontMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BadgeHeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BadgeLeftMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BadgeStrokeWidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("BadgeText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("BadgeTopMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BadgeWidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("CountryBold")
                        .HasColumnType("boolean");

                    b.Property<string>("CountryFontFamily")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("CountryFontMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CountryLeftMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CountryRightMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CountryText")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("CountryTopMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("HeaderBold")
                        .HasColumnType("boolean");

                    b.Property<string>("HeaderFontFamily")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("HeaderFontMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HeaderLeftMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("HeaderPrefix")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("HeaderRightMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HeaderTopMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("MarginBottomMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MarginLeftMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MarginRightMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MarginTopMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PrinterName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("ReferenceBold")
                        .HasColumnType("boolean");

                    b.Property<string>("ReferenceFontFamily")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("ReferenceFontMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ReferenceLeftMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ReferenceRightMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ReferenceTopMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("WarningBold")
                        .HasColumnType("boolean");

                    b.Property<string>("WarningFontFamily")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("WarningFontMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WarningLeftMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WarningRightMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("WarningText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("WarningTopMm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("ShippingLabelPrintSettings");
                });

            modelBuilder.Entity("backend.Models.SpecialProcessCertificateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalystId")
                        .HasColumnType("integer");

                    b.Property<string>("AnalystName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CertificateCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("ClienteNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EmissionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HardnessFound")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("HeatTreatLot")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Item")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Norma")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PurchasingOrder")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SpecialProcess")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("SpecialProcessId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SpecialProcessCertificates");
                });

            modelBuilder.Entity("backend.Models.SpecialProcessHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Changes")
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<int>("SpecialProcessId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecialProcessId");

                    b.ToTable("History_SpecialProcess");
                });

            modelBuilder.Entity("backend.Models.SpecialProcessModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Revision")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SpecialProcess")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Specification")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SpecialProcess");
                });

            modelBuilder.Entity("backend.Models.AnalystCertificateModel", b =>
                {
                    b.HasOne("backend.Models.AnalystModel", "Analyst")
                        .WithMany("Certificates")
                        .HasForeignKey("AnalystsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analyst");
                });

            modelBuilder.Entity("backend.Models.AnalystModel", b =>
                {
                    b.Navigation("Certificates");
                });
#pragma warning restore 612, 618
        }
    }
}
