CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Analysts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Analyst" character varying(120) NOT NULL,
    "Email" character varying(150),
    "Signature" text,
    "CreateBy" text NOT NULL,
    "UpdateBy" text NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdate" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Analysts" PRIMARY KEY ("Id")
);

CREATE TABLE "Cliente" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cliente" text NOT NULL,
    "Endereco" text,
    "CreateBy" text NOT NULL,
    "UpdateBy" text NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "LastUpdate" timestamp without time zone,
    CONSTRAINT "PK_Cliente" PRIMARY KEY ("Id")
);

CREATE TABLE "Controle_Eleb" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "OP_ELEB" text,
    "OP_Digicon" text,
    "PO_ELEB" text,
    "COD_ELEB" text,
    "Part_Number" text,
    "Valor_Peca" text,
    "Analise_PO" text,
    "Revisao_Desenho" text,
    "Qtd_Saldo" text,
    "Qtd_Lote" text,
    "Qtd_Saldo1" text,
    "Data_Envio_para_ELEB" timestamp without time zone,
    "NF_Faturada" text,
    "Decapagem" text,
    "SN_Decap" text,
    "CD" text,
    "SN_Peca" text,
    "Cliente" text,
    "Situacao" text,
    "Lote_ELEB" text,
    "Num_Certificado" text,
    "UpdateBy" text,
    CONSTRAINT "PK_Controle_Eleb" PRIMARY KEY ("ID")
);

CREATE TABLE "History_PartNumber" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartNumberId" integer NOT NULL,
    "Changes" text,
    "Observation" text,
    "ChangedBy" character varying(150) NOT NULL,
    "ChangedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_History_PartNumber" PRIMARY KEY ("Id")
);

CREATE TABLE "History_SpecialProcess" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SpecialProcessId" integer NOT NULL,
    "Changes" text,
    "Observation" text,
    "ChangedBy" character varying(150) NOT NULL,
    "ChangedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_History_SpecialProcess" PRIMARY KEY ("Id")
);

CREATE TABLE login_certification (
    username character varying(150) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(512) NOT NULL,
    salt character varying(512) NOT NULL,
    type character varying(50),
    image text,
    CONSTRAINT "PK_login_certification" PRIMARY KEY (username)
);

CREATE TABLE login_module_permissions (
    username character varying(150) NOT NULL,
    modulekey character varying(150) NOT NULL,
    canview boolean NOT NULL DEFAULT TRUE,
    canedit boolean NOT NULL DEFAULT FALSE,
    updatedat timestamp without time zone NOT NULL,
    CONSTRAINT "PK_login_module_permissions" PRIMARY KEY (username, modulekey)
);

CREATE TABLE login_password_resets (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    tokenhash character varying(64) NOT NULL,
    username character varying(150) NOT NULL,
    email character varying(255) NOT NULL,
    createdat timestamp without time zone NOT NULL,
    expiresat timestamp without time zone NOT NULL,
    usedat timestamp without time zone,
    CONSTRAINT "PK_login_password_resets" PRIMARY KEY (id)
);

CREATE TABLE login_sessions (
    sessionid uuid NOT NULL,
    username character varying(150) NOT NULL,
    email character varying(255),
    createdat timestamp without time zone NOT NULL,
    lastseen timestamp without time zone NOT NULL,
    revokedat timestamp without time zone,
    ipaddress character varying(64),
    useragent character varying(256),
    CONSTRAINT "PK_login_sessions" PRIMARY KEY (sessionid)
);

CREATE TABLE "OperationProcess" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OperationQuantity" text NOT NULL,
    "OperationDescription" text NOT NULL,
    "IsActivated" boolean NOT NULL,
    "CreateBy" text NOT NULL,
    "UpdateBy" text NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdate" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_OperationProcess" PRIMARY KEY ("Id")
);

CREATE TABLE "Parameters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartNumber" character varying(50) NOT NULL,
    "Processo" character varying(50) NOT NULL,
    "Norma" character varying(50) NOT NULL,
    "NormaRevision" character varying(10),
    "Parameter" character varying(100) NOT NULL,
    "Condition" character varying(100),
    "CreateBy" text NOT NULL,
    "UpdateBy" text NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdate" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Parameters" PRIMARY KEY ("Id")
);

CREATE TABLE "PartNumbers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartNumber" text NOT NULL,
    "Descricao" text NOT NULL,
    "Revision" text,
    "DrawingRevision" character varying(50),
    "ClienteId" integer,
    "ClienteNome" character varying(200),
    "IsActive" boolean NOT NULL,
    "CreateBy" text NOT NULL,
    "UpdateBy" text NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdated" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_PartNumbers" PRIMARY KEY ("Id")
);

CREATE TABLE "ProductConformityCertificates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CertificateNumber" text NOT NULL,
    "PartNumberId" integer,
    "PartNumber" text NOT NULL,
    "PartNumberDescription" text,
    "PartNumberRevision" text,
    "LotNumber" text,
    "Quantity" text,
    "CustomerPO" text,
    "Type" text,
    "SerialNumber" text,
    "InspectedAccording" text,
    "AnalystId" integer,
    "AnalystName" text,
    "DocumentNumber" text,
    "DocumentRevision" text,
    "DocumentDate" timestamp without time zone NOT NULL,
    "CustomerId" integer,
    "CustomerName" text,
    "CustomerAddress" text,
    "EmissionDate" timestamp without time zone NOT NULL,
    "CreateBy" text NOT NULL,
    "UpdateBy" text NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdate" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ProductConformityCertificates" PRIMARY KEY ("Id")
);

CREATE TABLE "ProductDocumentControls" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DocumentNumber" text NOT NULL,
    "DocumentRevision" text NOT NULL,
    "DocumentDate" timestamp without time zone NOT NULL,
    "InspectedAccording" text NOT NULL,
    "UpdateBy" text NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdate" timestamp without time zone,
    CONSTRAINT "PK_ProductDocumentControls" PRIMARY KEY ("Id")
);

CREATE TABLE "PurchaseOrders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PONumber" character varying(80) NOT NULL,
    "ClienteId" integer NOT NULL,
    "ClienteNome" character varying(200),
    "Item" character varying(80) NOT NULL,
    "Status" character varying(30) NOT NULL,
    "Comments" text,
    "CreateBy" text NOT NULL,
    "UpdateBy" text NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdate" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_PurchaseOrders" PRIMARY KEY ("Id")
);

CREATE TABLE "QualityCertificates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ControleElebId" integer,
    "NumeroCertificado" text,
    "Ordem" text,
    "OC" text,
    "Lote" text,
    "CodigoCliente" text,
    "PartNumber" text,
    "ValorPeca" text,
    "AnalisePo" text,
    "RevisaoDesenho" text,
    "Quantidade" text,
    "Decapagem" text,
    "SNDecapagem" text,
    "CDChamado" text,
    "Cliente" text,
    "Fornecedor" text,
    "RelatorioInspecao" text,
    "CertificadoMP" text,
    "Responsavel" text,
    "AnalystId" integer,
    "AnalystName" character varying(150),
    "DesenhoLP" text,
    "Observacoes" text,
    "SNPeca" text,
    "TipoEnvio" text,
    "DescricaoOperacao" text,
    "Data" timestamp without time zone NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "UpdateBy" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_QualityCertificates" PRIMARY KEY ("Id")
);

CREATE TABLE "RNC" (
    "CodeMach" text,
    "Operator" text,
    "IndProd1" text,
    "IndProd3" text,
    "QntdNC" integer,
    "Data1" text,
    "Data2" text,
    "DataGerado" timestamp without time zone,
    "Cliente" text,
    "Causador" text
);

CREATE TABLE "ShippingLabelPrintSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(100) NOT NULL,
    "WidthMm" numeric(10,2) NOT NULL,
    "HeightMm" numeric(10,2) NOT NULL,
    "MarginLeftMm" numeric(10,2) NOT NULL,
    "MarginTopMm" numeric(10,2) NOT NULL,
    "MarginRightMm" numeric(10,2) NOT NULL,
    "MarginBottomMm" numeric(10,2) NOT NULL,
    "BadgeLeftMm" numeric(10,2) NOT NULL,
    "BadgeTopMm" numeric(10,2) NOT NULL,
    "HeaderLeftMm" numeric(10,2) NOT NULL,
    "HeaderTopMm" numeric(10,2) NOT NULL,
    "HeaderRightMm" numeric(10,2) NOT NULL,
    "CountryLeftMm" numeric(10,2) NOT NULL,
    "CountryTopMm" numeric(10,2) NOT NULL,
    "CountryRightMm" numeric(10,2) NOT NULL,
    "WarningLeftMm" numeric(10,2) NOT NULL,
    "WarningTopMm" numeric(10,2) NOT NULL,
    "WarningRightMm" numeric(10,2) NOT NULL,
    "ReferenceLeftMm" numeric(10,2) NOT NULL,
    "ReferenceTopMm" numeric(10,2) NOT NULL,
    "ReferenceRightMm" numeric(10,2) NOT NULL,
    "BadgeFontMm" numeric(10,2) NOT NULL,
    "HeaderFontMm" numeric(10,2) NOT NULL,
    "CountryFontMm" numeric(10,2) NOT NULL,
    "WarningFontMm" numeric(10,2) NOT NULL,
    "ReferenceFontMm" numeric(10,2) NOT NULL,
    "BadgeBold" boolean NOT NULL,
    "HeaderBold" boolean NOT NULL,
    "CountryBold" boolean NOT NULL,
    "WarningBold" boolean NOT NULL,
    "ReferenceBold" boolean NOT NULL,
    "BadgeText" character varying(50) NOT NULL,
    "HeaderPrefix" character varying(120) NOT NULL,
    "AssyHeaderPrefix" character varying(120) NOT NULL,
    "CountryText" character varying(80) NOT NULL,
    "WarningText" character varying(200) NOT NULL,
    "BadgeFontFamily" character varying(80) NOT NULL,
    "HeaderFontFamily" character varying(80) NOT NULL,
    "CountryFontFamily" character varying(80) NOT NULL,
    "WarningFontFamily" character varying(80) NOT NULL,
    "ReferenceFontFamily" character varying(80) NOT NULL,
    "BadgeWidthMm" numeric(10,2) NOT NULL,
    "BadgeHeightMm" numeric(10,2) NOT NULL,
    "BadgeStrokeWidthMm" numeric(10,2) NOT NULL,
    "PrinterName" character varying(200),
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdate" timestamp without time zone,
    CONSTRAINT "PK_ShippingLabelPrintSettings" PRIMARY KEY ("Id")
);

CREATE TABLE "ShippingLabels" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PartNumberId" integer NOT NULL,
    "PartNumber" character varying(150) NOT NULL,
    "ReferenceDate" timestamp without time zone NOT NULL,
    "RangeStart" integer NOT NULL,
    "RangeEnd" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "LabelModel" character varying(30) NOT NULL,
    "BadgeFontMm" numeric(10,2) NOT NULL,
    "HeaderFontMm" numeric(10,2) NOT NULL,
    "CountryFontMm" numeric(10,2) NOT NULL,
    "WarningFontMm" numeric(10,2) NOT NULL,
    "ReferenceFontMm" numeric(10,2) NOT NULL,
    "BadgeWidthMm" numeric(10,2) NOT NULL,
    "BadgeHeightMm" numeric(10,2) NOT NULL,
    "BadgeStrokeWidthMm" numeric(10,2) NOT NULL,
    "LabelWidthMm" numeric(10,2) NOT NULL,
    "LabelHeightMm" numeric(10,2) NOT NULL,
    "MarginLeftMm" numeric(10,2) NOT NULL,
    "MarginTopMm" numeric(10,2) NOT NULL,
    "MarginRightMm" numeric(10,2) NOT NULL,
    "MarginBottomMm" numeric(10,2) NOT NULL,
    "BadgeLeftMm" numeric(10,2) NOT NULL,
    "BadgeTopMm" numeric(10,2) NOT NULL,
    "HeaderLeftMm" numeric(10,2) NOT NULL,
    "HeaderTopMm" numeric(10,2) NOT NULL,
    "HeaderRightMm" numeric(10,2) NOT NULL,
    "CountryLeftMm" numeric(10,2) NOT NULL,
    "CountryTopMm" numeric(10,2) NOT NULL,
    "CountryRightMm" numeric(10,2) NOT NULL,
    "WarningLeftMm" numeric(10,2) NOT NULL,
    "WarningTopMm" numeric(10,2) NOT NULL,
    "WarningRightMm" numeric(10,2) NOT NULL,
    "ReferenceLeftMm" numeric(10,2) NOT NULL,
    "ReferenceTopMm" numeric(10,2) NOT NULL,
    "ReferenceRightMm" numeric(10,2) NOT NULL,
    "BadgeBold" boolean NOT NULL,
    "HeaderBold" boolean NOT NULL,
    "CountryBold" boolean NOT NULL,
    "WarningBold" boolean NOT NULL,
    "ReferenceBold" boolean NOT NULL,
    "BadgeText" character varying(50) NOT NULL,
    "HeaderPrefix" character varying(120) NOT NULL,
    "AssyHeaderPrefix" character varying(120) NOT NULL,
    "CountryText" character varying(80) NOT NULL,
    "WarningText" character varying(200) NOT NULL,
    "BadgeFontFamily" character varying(80) NOT NULL,
    "HeaderFontFamily" character varying(80) NOT NULL,
    "CountryFontFamily" character varying(80) NOT NULL,
    "WarningFontFamily" character varying(80) NOT NULL,
    "ReferenceFontFamily" character varying(80) NOT NULL,
    "PrinterName" character varying(200),
    "CreateBy" character varying(100) NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdate" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ShippingLabels" PRIMARY KEY ("Id")
);

CREATE TABLE "SpecialProcess" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SpecialProcess" character varying(50) NOT NULL,
    "Specification" character varying(20),
    "Revision" character varying(10),
    "Comment" text,
    "CreateBy" text NOT NULL,
    "UpdateBy" text NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdate" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_SpecialProcess" PRIMARY KEY ("Id")
);

CREATE TABLE "SpecialProcessCertificates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CertificateCode" character varying(15) NOT NULL,
    "ClienteId" integer,
    "ClienteNome" character varying(200),
    "SpecialProcessId" integer,
    "SpecialProcess" character varying(120),
    "Norma" character varying(150),
    "PartNumber" character varying(100),
    "EmissionDate" timestamp without time zone NOT NULL,
    "Quantity" numeric(18,2) NOT NULL,
    "LotNumber" character varying(120),
    "PurchasingOrder" character varying(120),
    "Item" character varying(80),
    "HardnessFound" character varying(120),
    "HeatTreatLot" character varying(120),
    "AnalystId" integer,
    "AnalystName" character varying(150),
    "Observations" text,
    "CreateBy" text,
    "UpdateBy" text,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdate" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_SpecialProcessCertificates" PRIMARY KEY ("Id")
);

CREATE TABLE "TechnicalStandards" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Cliente" text NOT NULL,
    "Processo" text NOT NULL,
    "Norma" text NOT NULL,
    "Revision" text,
    "CreateBy" text NOT NULL,
    "UpdateBy" text NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdated" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_TechnicalStandards" PRIMARY KEY ("Id")
);

CREATE TABLE "AnalystsCertificate" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Certificate" integer NOT NULL,
    "IsDefault" boolean NOT NULL,
    "AnalystsId" integer NOT NULL,
    "CreateBy" text NOT NULL,
    "UpdateBy" text NOT NULL,
    "CreateDate" timestamp without time zone NOT NULL,
    "LastUpdated" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_AnalystsCertificate" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AnalystsCertificate_Analysts_AnalystsId" FOREIGN KEY ("AnalystsId") REFERENCES "Analysts" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AnalystsCertificate_AnalystsId" ON "AnalystsCertificate" ("AnalystsId");

CREATE UNIQUE INDEX "IX_AnalystsCertificate_Certificate_IsDefault" ON "AnalystsCertificate" ("Certificate", "IsDefault") WHERE "IsDeleted" = FALSE AND "IsDefault" = TRUE;

CREATE INDEX "IX_History_PartNumber_PartNumberId" ON "History_PartNumber" ("PartNumberId");

CREATE INDEX "IX_History_SpecialProcess_SpecialProcessId" ON "History_SpecialProcess" ("SpecialProcessId");

CREATE UNIQUE INDEX "IX_login_certification_email" ON login_certification (email);

CREATE INDEX "IX_login_module_permissions_username" ON login_module_permissions (username);

CREATE UNIQUE INDEX "IX_login_password_resets_tokenhash" ON login_password_resets (tokenhash);

CREATE INDEX "IX_login_password_resets_username_email" ON login_password_resets (username, email);

CREATE INDEX "IX_login_sessions_lastseen" ON login_sessions (lastseen);

CREATE INDEX "IX_login_sessions_username" ON login_sessions (username);

CREATE UNIQUE INDEX "IX_PurchaseOrders_PONumber_Item_ClienteId" ON "PurchaseOrders" ("PONumber", "Item", "ClienteId") WHERE "IsDeleted" = FALSE;

CREATE UNIQUE INDEX "IX_ShippingLabelPrintSettings_Username" ON "ShippingLabelPrintSettings" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260820145633_InitialPostgreSql', '8.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO login_certification (username, email, password, salt, type, image)
SELECT
    'admin',
    'admin@local',
    '8qJ41ssDJ7QzHt78XL1LFB7syHiGPQtHgMVIkSSum8U=',
    'a11iPaN6gXf0bL5H2HJWjg==',
    'Admin',
    NULL
WHERE NOT EXISTS (
    SELECT 1
    FROM login_certification
    WHERE LOWER(username) = 'admin'
       OR LOWER(email) = 'admin@local'
)
ON CONFLICT DO NOTHING;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260820150858_SeedMasterAdmin', '8.0.11');

COMMIT;

